### ISSUE TITLE
need to either add the instance to a public subnet or set up a NAT Gateway.

### ISSUE THREAD

**Issue by kr1json** [abdullahkhawer/mongodb-cluster-on-aws-ecs#3]
unable to install AWS CLI on the instance, and even after installing AWS CLI using yum, I am unable to access Route 53.

Is there any other solution?

**Comment by abdullahkhawer** [comment]
Hi @kr1json ,
Thanks for reaching out.
Did the Terraform deployment succeed?
Which part of the code failed?
On which instance are you trying to access AWS Route 53?

**Comment by abdullahkhawer** [comment]
@kr1json, If this is related to downloads performed on AWS EC2 instances via the `user_data.sh` script, you need to create a NAT gateway under AWS VPC. This allows the AWS EC2 instances in private subnets to access the internet for downloading various tools (e.g., AWS CLI, Unzip, MongoDB, etc). Even if you create a VPC endpoint for AWS Route 53, you still need a NAT gateway to access other resources on the internet.

**Comment by JongSeok-Kim** [comment]
Hi @abdullahkhawer 
That's correct. I resolved the issue by adding a NAT Gateway. I mentioned it because it wasn't included in the README.
Thank you for sharing such great code.

In the terraform-usage-example.tf example, t3.small is 2048, but why did you allocate 1648 CPU for the task? Is there any reason why 2048 couldn’t be allocated, or are there any considerations to keep in mind when doing so?

**Comment by kr1json** [comment]
Hi @abdullahkhawer
That's correct. I resolved the issue by adding a NAT Gateway. I mentioned it because it wasn't included in the README.
Thank you for sharing such great code.

In the terraform-usage-example.tf example, t3.small is 2048, but why did you allocate 1648 CPU for the task? Is there any reason why 2048 couldn’t be allocated, or are there any considerations to keep in mind when doing so?

**Comment by abdullahkhawer** [comment]
> That's correct. I resolved the issue by adding a NAT Gateway.

@kr1json , Glad to hear that your issue is resolved.

> I mentioned it because it wasn't included in the README.

Thanks for highlighting that though.
I have updated the prerequisites section in the README and mentioned NAT gateway in it.

> Thank you for sharing such great code.

Welcome, the pleasure is all mine.
The purpose was to help others who want to implement the same to save their time and effort.

> In the terraform-usage-example.tf example, t3.small is 2048, but why did you allocate 1648 CPU for the task? Is there any reason why 2048 couldn’t be allocated, or are there any considerations to keep in mind when doing so?

AWS ECS task uses "CPU units" to manage processing power, with `1024` units equal to 1 vCPU. A `t3.small` instance provides `2048` CPU units (2 vCPUs). Assigning all `2048` units to a task uses the instance’s full capacity, leaving no room for system or background processes, which may lead to throttling. To avoid this, I set it to a lower value which is `1648`, to reserve some capacity (e.g., 400 units) for smoother operation and better system performance.
So, that is the reasoning behind that but you can set the instance type, CPU and memory to any desired values.

Is there anything else I can help you with?

**Comment by kr1json** [comment]
Thank you for your help. Thanks to your code, I was able to set up MongoDB easily and quickly.

**Comment by abdullahkhawer** [comment]
Welcome. 🙂
